### PR TITLE
Fix bug when several channel group inside one folder.

### PR DESCRIPTION
**Pull request by samuelgarcia**
this is a small bug fix to autoselect the good channel group in tridesclous folder.

needed for sorter in class.

### CODE REVIEW

**Comment by colehurwitz31** [comment]
Great! Will merge

**Comment by colehurwitz31** [comment]
I fixed some of the english if that is ok. :)

**Comment by samuelgarcia** [comment]
Thank you, my english is so bad.

**Comment by colehurwitz31** [comment]
No worries! My French is much worse!!

**Pull request merged**
