### PR TITLE
Remove comparision deprecation warning

### PR DESCRIPTION
**Pull request by h-mayorquin**
Remove deprecation warnings from comparison with unequal channels.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@alejoe91 I know this is in LEGACY status, but the CI here also shows what we found on NCT with regards to the new SpikeGLX file on GIN

@samuelgarcia if you think back-compatibility of testing infrastructure is worth it, maybe add back the original `Noise4Sam` in a different directory (that we can avoid installing on the modern tests) so it can be used previously?

Or another possibility perhaps, is it possible to install particular versions (identified I assume by the hashes) of a GIN repo through datalad? @yarikoptic @JuliaSprenger

**Comment by h-mayorquin** [comment]
Thanks, @CodyCBakerPhD 

Related:
https://github.com/catalystneuro/nwb-conversion-tools/pull/560

**Comment by JuliaSprenger** [comment]
Hi @CodyCBakerPhD I am not sure what exactly you are aiming to fix here, but yes you can checkout a specific branch or commit accessing git via datalad, e.g. `dataset.repo.call_git(['checkout', 'main'])`, where dataset is your datalad dataset instance, as for example here: https://github.com/SpikeInterface/spikeextractors/blob/dff4dccfdd156b15d96608b0865e5895a743ea9f/tests/test_gin_repo.py#L23

**Comment by yarikoptic** [comment]
> Or another possibility perhaps, is it possible to install particular versions (identified I assume by the hashes) of a GIN repo through datalad? @yarikoptic @JuliaSprenger

in case of no submodules: @JuliaSprenger 's answer is a good one! Also there is `git_clone_opts=None,` option to datalad's `clone` if that is the one you use  -- then you could pass `git_clone_opts=["-b", "main"]`.  if you have submodules -- install top dataset into correct branch and then install subdatasets.
But what problem you are trying to solve?

**Comment by CodyCBakerPhD** [comment]
> But what problem you are trying to solve?

version A of the dataset contains a file structured in a certain way that the software here is built around, which is a small part of upstream tests as well.

version B of the dataset took that file and altered it in ways that break this software, so now the tests here (and upstream) fail.

We can't update the actual software here to be compatible here because it's in LEGACY status, so it makes more sense to 'freeze' the version of the testing dataset that this testing suite uses.

**Pull request merged**
