### PR TITLE
Implement get_ttl_events method for available extractors

### PR DESCRIPTION
**Pull request by alejoe91**
This PR implements the `get_ttl_events` method, which returns the frame time of digital channels used for synchronization.

The method signature is : `get_ttl_events(self, start_frame=None, end_frame=None, channel_id=0)`, where `channel_id` is the channel of the digital signal to be returned. 

The method returns:
- ttl_frames: np.array with frames at which TTL occur
- ttl_state: np.array of the same length with +1 (rising) and -1 (falling) 

Currently implemented in:
- SubRecordingExtractor
- MultiRecordingTimeExtractor
- NumpyRecrdingExtractor (for adde tests)
- SpikeGLXRecordingExtractor
- OpenEphysRecordingExtractor
- IntanRecordingExtractor
- Mea1kRecordingExtractor
- MaxOneRecordingExtractor

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Alessio.
Can we have a call for this API extention ?

**Comment by colehurwitz** [comment]
Should we make: channel --> channel_id/channel_ids to be consistent?

**Comment by colehurwitz** [comment]
I have been quite busy with other work, but will try to be more helpful on github as well!

**Comment by alejoe91** [comment]
@samuelgarcia Neo extractors should also implement this! But we can add it later. For me this is ready to be merged

**Comment by samuelgarcia** [comment]
@alejoe91 : I am not super happy ith the happy. I hink we should have 2 layer to get theses ttl frames one would be to have the boolean time series and the other would be the have the up and down edge (like you did here). Give by defult the edge can have super big cost for long files.
Could we have a discussion at least for the API ?

**Pull request merged**
