### PR TITLE
improve mda extractor and allow unit properties to bet get/set for multiple units at once

### PR DESCRIPTION
**Pull request by magland**
improve mdaextractor behavior for remote files
enable setting property of multiple units simultaneously
implement getUnitPropertyNames
allow getUnitProperty for multiple units

### CODE REVIEW

**Comment by colehurwitz31** [comment]
I don’t know about unit_id being a list also. It would have to be unit_ids i think

**Comment by magland** [comment]
I think we should make an additional function instead -- I am beginning to use the framework and do think that getting/setting multiple at a time is important.

How about one of the following:

sorter.setUnitsProperty(unit_ids, property_name, values)
sorter.setUnitPropertyMulti(unit_ids, property_name, values)
(I don't think setUnitProperties is correct, although it sounds better)

I vote for setUnitsProperty

**Comment by magland** [comment]
Yes. I'll adjust the pull request accordingly and then we can discuss.

**Comment by magland** [comment]
I updated the pull request accordingly (although haven't yet implemented getChannelsProperty)

**Pull request merged**
