### PR TITLE
added save_si function

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@alejoe91 @luiztauffer Let me know if you'd like this moved to a particular corner of this ecosystem, or even a different repo.

### CODE REVIEW

**Comment by luiztauffer** [comment]
is this only for `nwb-conversion-tools` or for a more general use?

**Comment by alejoe91** [comment]
@CodyCBakerPhD I think we could leave it here! It's general quite general purpose and SI specific. Note that in the new api this dmstrategy is implemented directly in the base class

**Comment by CodyCBakerPhD** [comment]
@alejoe91 Yeah, this is very particular to the legacy version of spikeextractors that will be left behind when the new API is released. Good to hear it's that ingrained in the new API though!

**Comment by alejoe91** [comment]
@CodyCBakerPhD all tests are failing due to some import issues. Can you try importing the cache extractors from relative paths?

**Comment by CodyCBakerPhD** [comment]
@alejoe91 OK tests should be passing now. Not actually an issue of relative imports per se but rather than having a function within the extraction_tools umbrella that imports classes like RecordingExtractor, etc, causes a circular import because those all use extraction tool functions as well. I simply moved it to a different location and it resolved the circulatirty.

**Pull request merged**
