### PR TITLE
Implement a simple format based on npz

### PR DESCRIPTION
**Pull request by samuelgarcia**
@alejoe91 @colehurwitz : I have implemented a very simple file format for sortign extractor.
I will be usefull to share result and send results for coprarison.

It use the NPZ from numpy format. Very simple.
Internally it store unit_ids+times+labels as vetor (+optional sampling_frequency very soon)

If it is OK for you could we merge this. I will add some function in spiketoolkit that will need this.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Very cool! Will merge

**Comment by samuelgarcia** [comment]
Oh thank you.
You are super fast merger!

**Comment by colehurwitz** [comment]
From working with you Samuel, I know that pretty much all of your code is trustworthy and clean. Checking it doesn't take super long. :)

**Comment by samuelgarcia** [comment]
Thanks.

**Pull request merged**
