### PR TITLE
parse dtype as str (for numpy dtypes)

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I am not sur at all this is a good idea.
Why are you doing this ?

**Comment by alejoe91** [comment]
because it fails if the type is a numpy.dtype. The startswith doesn't work

**Comment by alejoe91** [comment]
and it was breaking our entire pipeline :P

**Comment by samuelgarcia** [comment]
And now it is breaking mine ;)

**Comment by alejoe91** [comment]
Oh no!! ok sorry about that :) What can we do then? maybe check uint only if not isinstance(self._dtype, numpy.dtype)? 

How is it breaking your code?

**Comment by colehurwitz** [comment]
So the dtype is now a string? Like 'int' or something? What are the options that can be passed in for np.dtypes. Having it as a string will be useful for the GUI since strings are easiest

**Comment by samuelgarcia** [comment]
@alejoe91 it was a joke.

**Comment by samuelgarcia** [comment]
I think the good pratice is to do:
```python
def my_fun(self, dtype):
    self._dtype= np.dtype(dtype) # so  always a dtype

# and make test like this

if self._dtype.str.startswith(...)
```

**Comment by samuelgarcia** [comment]
You also have dtype.kind.

real dtype have convinient methods.

**Comment by samuelgarcia** [comment]
But no worry I don't care at the end.

**Comment by alejoe91** [comment]
ahahahah I took it seriously. `self._dtype.str.startswith(...)` this looks good!

**Pull request merged**
