### PR TITLE
Improve writeBinaryDatFormat:

### PR DESCRIPTION
**Pull request by samuelgarcia**
* dtype=None by default
  * chunksize copy when chunksize is not None

This is about theses problems:
#103 #104 
https://github.com/SpikeInterface/spiketoolkit/issues/72

### CODE REVIEW

**Comment by colehurwitz31** [comment]
Yes, these changes are good. We can merge when it is ready.

**Comment by colehurwitz31** [comment]
I also think that explicit kargs like time_axis=0 or time_axis=1 would be good for this and would make it more intuitive.

**Comment by samuelgarcia** [comment]
OK, so I will do the change time_axis instead of transpose.
Wait before the merge.

@alejoe91 : about the possible bug in klusta and kilosort ?

**Comment by samuelgarcia** [comment]
Oups it appear that I was doing a transpose when tranpose=True but in fact this is the reverse.

**Comment by alejoe91** [comment]
maybe `transpose=True` by default?

**Comment by alejoe91** [comment]
or time_axis=1

**Comment by samuelgarcia** [comment]
The correct way for theses files was transpose=False and so time_axis=0.

I really would vote for the default behavior to write the file in the correct order.

**Comment by alejoe91** [comment]
when transpose was False the files were actually transpose though

**Comment by samuelgarcia** [comment]
I don't get it.

What I anderstand is transpose=False the getTrace() are transposed so files are in the correct way (sample, channels).

**Comment by alejoe91** [comment]
Correct :) but now the data are transposed only if transpose=True. So I suggest using transpose=True by default, as in klusta and kilosort the transpose arg is not used

**Comment by alejoe91** [comment]
Ooook! My bad. time_axis=0 is the correct (default) behavior. Sorry for the confusion ;)

**Comment by alejoe91** [comment]
Ooook! My bad. time_axis=0 is the correct (default) behavior. Sorry for the confusion ;)

**Comment by samuelgarcia** [comment]
I change transpose to time_axis to make it less ambiguous for all of us.

If you are happy with this you can merge.

I need this for a refactoring in spiketoolkit.

**Comment by alejoe91** [comment]
good for me :)

Merging

**Comment by samuelgarcia** [comment]
Thanks.

**Pull request merged**
