### PR TITLE
Refactor spikeextractors to snake case

### PR DESCRIPTION
**Pull request by colehurwitz31**
All snake_case. If we approve and merge, then I will push a new tag (0.4.0) and then update spiketoolkit and spikewidgets.

### CODE REVIEW

**Comment by magland** [comment]
This looks good, but I guess we should wait until the unit tests have passed.

**Comment by colehurwitz31** [comment]
All done! Last failing MEArec test was fixed by Alessio

**Comment by magland** [comment]
Great!

**Comment by colehurwitz31** [comment]
Should I merge?

**Pull request merged**
