### PR TITLE
Made get unit ids return a numpy array in CurationSortingExtractor

### PR DESCRIPTION
**Pull request by colehurwitz**

### CODE REVIEW

**Comment by colehurwitz** [comment]
Any issues with this? I will merge this since i don't think it should be a problem

**Comment by samuelgarcia** [comment]
I thougth the API was a list.
Some extractor return a list.
It should be always teh same and tested.

**Comment by colehurwitz** [comment]
Sorry for merging this!!

> I thougth the API was a list.

The API says that it can be either a list or a 1D numpy array. I would argue that either works, but we should choose one.

**Comment by colehurwitz** [comment]
```
@abstractmethod
    def get_unit_ids(self):
        '''This function returns a list of ids (ints) for each unit in the recording.
        Returns
        ----------
        unit_ids: array_like
            A list or 1D array of the unit ids in recording (ints).
        '''
        pass
```

**Comment by colehurwitz** [comment]
I am making an issue to discuss. Sorry for merging, I didn't think anyone was gonna read this small change, but I was wrong.

**Pull request merged**
