### PR TITLE
Allow relative paths in dumping

### PR DESCRIPTION
**Pull request by alejoe91**
- remove warning for h5py > 3

### CODE REVIEW

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/issues/133#issuecomment-832431817

**Comment by samuelgarcia** [comment]
Hi
Could you also propagate this concept in the new branch ?

**Comment by alejoe91** [comment]
Yep! Already on it ;)

**Comment by samuelgarcia** [comment]
For the new one. In my mind, when dumping to json, it will always relative to the JSON file itself, no ?

**Comment by alejoe91** [comment]
@samuelgarcia https://github.com/SpikeInterface/spikeinterface/pull/136

**Pull request merged**
