### PR TITLE
Draft for spikegadgets.

### PR DESCRIPTION
**Pull request by samuelgarcia**
Depend on on working branch here https://github.com/NeuralEnsemble/python-neo/pull/954

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@Saksham20 this should work with my neo branch. Here you have to select one unique stream.

**Comment by alejoe91** [comment]
@samuelgarcia is the new version of NEO release?

**Comment by samuelgarcia** [comment]
Not release but in the master yet.

**Comment by samuelgarcia** [comment]
Merge this even if spikegadgets will not work

**Pull request merged**
