### PR TITLE
add get_conversion_factor

### PR DESCRIPTION
**Pull request by bendichter**
to RecordingExtractor, NumpyRecordingExtractor, and NwbRecordingExtractor

fix https://github.com/SpikeInterface/spikeextractors/issues/227

### CODE REVIEW

**Comment by colehurwitz** [comment]
My recommendation would be to make conversion factor=1 by default (in RecordingExtractor) and then have get_conversion_factor return that as normal. 

Then, we can override specific conversion factors in the given extractors as needed, but by default, all the tests will pass.

**Comment by colehurwitz** [comment]
Also, the spikeglx changes look good :)

**Comment by bendichter** [comment]
We have an issue with spikeglx. All of the channels have unique gains.

**Comment by colehurwitz** [comment]
We could have gain be a channel property that is loaded in then during initialisation.

**Comment by alejoe91** [comment]
We could have the conversion factor be either a scalar (if the same for all channels) or an array. In the second case we can load it as a property and use channel-specific gains in the get_traces

**Comment by colehurwitz** [comment]
I would load the scalar as a channel property for each channel as well potentially, just to be consistent. Then we can do the same procedure in get traces regardless of the gain being a scalar or an array.

**Comment by bendichter** [comment]
@colehurwitz @alejoe91 I hadn't thought of using the electrode properties. I think of gain more as a property of the dataset than a property of the channel. That approach wouldn't work for NWB:N because electrodes might be associated with multiple datasets that could potentially have different gains. Making `gain` a property of each electrode could work in your system if you are sure that you'll only have on dataset per channel, and doing it this way in SI and storing it differently in NWB:N would be fine.

**Comment by colehurwitz** [comment]
@bendichter @luiztauffer So I implemented the conversion factor already, but the SpikeGLX changes are still very useful. Could one of you make a pull request with just the spikeglx changes?

**Comment by colehurwitz** [comment]
Just enquiring about the spikeglx question above. Can we still use that and forget about the other part of the pull request?

**Comment by bendichter** [comment]
Yeah that's the plan, we just had some pressing issues that took priority
over the last week. We'll get back to this over the next week

**Pull request closed without merging**
