### PR TITLE
jump to next channel group if no clusters in channel group

### PR DESCRIPTION
**Pull request by lepmik**

### CODE REVIEW

**Comment by colehurwitz31** [comment]
Unless I am missing something, won't this have the same behavior as before?

The try catch block just continues if there are no clusters and then it still tries to do the for loop

**Comment by lepmik** [comment]
Is it not continuing to next iteration in the current loop - skipping whatevers beneath?

**Comment by alejoe91** [comment]
@colehurwitz31 @lepmik Yes the continue stops the current iteration and continues to the next. This should fix the problem :)

**Comment by colehurwitz31** [comment]
Ah yes, my bad, just tested it

**Comment by colehurwitz31** [comment]
I will merge

**Pull request merged**
