### PR TITLE
Bug when grp is not an int.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : could you check this ?
This prevent plot_1_preprocessing example to work correctly.

**Comment by alejoe91** [comment]
Hi Sam, I don't think that's correct because channel groups could be shuffled. Why is it failing with the other code? It's parsed as int

**Comment by samuelgarcia** [comment]
I agree this is bad.
But look at **plot_1_preprocessing** in si please.

**Comment by samuelgarcia** [comment]
Oups sorry this is **plot_3_sorting_by_group**

**Comment by alejoe91** [comment]
Ahhhh! ok I think the problem is that groups can be `str` as well :)

**Comment by alejoe91** [comment]
fixing here instead: https://github.com/SpikeInterface/spikesorters/pull/104

**Comment by samuelgarcia** [comment]
We can close.

**Pull request closed without merging**
