### PR TITLE
Add `is_filtered` to BaseExtractor

### PR DESCRIPTION
**Pull request by alejoe91**
This makes it easy to know if a RecordingExtractor is filtered or not (especially for spiketoolkit)

### CODE REVIEW

**Comment by alejoe91** [comment]
@colehurwitz this is useful for not re-filtering in validation and curation if recordings are already filtered

**Comment by samuelgarcia** [comment]
Good idea. Maybe it could be more formal and have list of "done preprocessing" (like whittening) that would also contain a dict with args of theses steps.

**Comment by samuelgarcia** [comment]
Or changed this attributes self.is_filtered to self.is_preprocessed
This is more generic and less ambiguous.

**Comment by alejoe91** [comment]
I think that `is_filtered` is of particular importance and stronger than `is_processed`. Currently is_filtered is only changed by the `bandpass_filter`. We can think about other more generic approaches if needed in the future.

**Pull request merged**
