### PR TITLE
Spike glx

### PR DESCRIPTION
**Pull request by bendichter**
Use standard SpikeGLX libraries to make data access more robust and to include meta-data which allows you to convert to uV

### CODE REVIEW

**Comment by colehurwitz** [comment]
Awesome! Really nice changes. Looks good to me.

**Comment by bendichter** [comment]
@colehurwitz yes, ready to merge from our end!

**Comment by alejoe91** [comment]
ok let's merge then :)

**Comment by bendichter** [comment]
fyi @kristinquick

**Pull request merged**
