### PR TITLE
Test multiplatform jobs on travis

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I am not in favor of testing multiple version of python here.
This is totally insane regarding the power consumption it imply.
We  have a nich project we few user.
This would make sens wich some thousands of users.

**Comment by alejoe91** [comment]
Ok but at least Linux and windows

**Comment by samuelgarcia** [comment]
win + linux : ok
all combinaison of os X py_version : not green compatible
does travis support window now ?

**Comment by alejoe91** [comment]
Yep! Beta version

**Comment by samuelgarcia** [comment]
cool.
I was not aware of this.

**Comment by alejoe91** [comment]
@samuelgarcia I had to make those changes to the `ChacheRecordingExtractor` in order to avoid windows PermissionErrors.
Probably related to this https://github.com/SpikeInterface/spikesorters/issues/163?

**Pull request merged**
