### PR TITLE
add neuroscope (name TBD) format extractor

### PR DESCRIPTION
**Pull request by alexmorley**
To do:

- [ ] Add test?
- [ ] Check for overlap.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Looks good! Do you want to add a unit test for it? We can add it as well.

**Comment by alejoe91** [comment]
@alexmorley is this for a specific sorter or a suggestion for a simple and universal format? 
In the second case, I think it would be nice to also store the sampling frequency, since now also sorting extractors have the get_sampling_frequency function.
Maybe a params.json?

**Comment by samuelgarcia** [comment]
neuroscope is already in neo.rawio.
I plan to make neo base extractor this autum.
So this extractor woule be also ported also.

**Comment by alexmorley** [comment]
@alejoe91 yeah it is that. I will add that sometime this week :)

**Comment by alejoe91** [comment]
Great! Let us know when you ar ready to merge.

@samuelgarcia let's aim for october/november to move the base extractors on neo.rawio :)

**Comment by samuelgarcia** [comment]
@alejoe91 : which year ?

**Comment by alejoe91** [comment]
@alexmorley any updates? :)

**Comment by bendichter** [comment]
Hey what's the status of this? I would like to use it.

**Comment by alexmorley** [comment]
@bendichter We need to write a test for it and before we can merge. If you would be keen to write a basic test I'd be happy to review and help get it in quickly (don't have time to do this from scratch right now).

**Comment by bendichter** [comment]
@alexmorley got it. Thanks for all the hard work so far. I'll talk to my team and see if we can help carry this to the finish

**Comment by alejoe91** [comment]
@alexmorley @bendichter why don't we merge this and write a simple test later? The test basically saves a simulated dataset with the write function and loads it back to memory. Nothing super fancy

**Comment by bendichter** [comment]
Sounds good to me

**Pull request merged**
