### PR TITLE
unique id (from counter)

### PR DESCRIPTION
**Pull request by colehurwitz**
I wanted a unique ID for each extractor that was created in a session. This is useful for naming temporary files, etc., when working with many Recordings and Sortings. What do you think @samuelgarcia ?

### CODE REVIEW

**Comment by alejoe91** [comment]
Are you sure that this would be updated by initializing multiple extractors?

**Comment by colehurwitz** [comment]
I can add a test for it. I tried it with multiple extractors and multiple subextractors and it worked.

**Comment by alejoe91** [comment]
Let's see what Sam says :)

**Comment by colehurwitz** [comment]
Sure, i wanted a unique identifier so I could save out temporary files like this:

`file_name = 'recording_' + str(recording.id)`

**Comment by colehurwitz** [comment]
Whoops, didn't realize that referencing this PR elsewhere would do this... this PR has nothing to do with NEO!

**Comment by samuelgarcia** [comment]
Hi Cole.
I am OK with this if you need this for your workflow.
The only drwback I can see is that if you run in parralel in 2 python interpreters then this ID will unique inside each interpreters but not globally unique and so if you use this ID to generate temporary files you could have colision. No ?

**Comment by colehurwitz** [comment]
Is there a way to make something like this work in different interpreters or is that impossible?

**Comment by samuelgarcia** [comment]
Maybe with random at unit and then counter.

**Comment by colehurwitz** [comment]
I think actually just giving a random number upon init should work. I removed the counter because it doesn't really add much when making temporary files.

**Pull request merged**
