### PR TITLE
changes to bindat

### PR DESCRIPTION
**Pull request by colehurwitz**
frames_first=True --> time_axis = 0

### CODE REVIEW

**Comment by colehurwitz** [comment]
@alejoe91

**Comment by alejoe91** [comment]
I'll double check this and merge tomorrow

**Comment by samuelgarcia** [comment]
Hi Cole and Allessio, please have a look everywhere if if do not break old codes (in tutorial, comparison study...)

**Comment by colehurwitz** [comment]
Basically, you will have to reverse the boolean in a bunch of bindat calls (one in spiketoolkit and some in spikesorters). It is a bit tricky to catch all the cases. I would do it, but I will not be in and have to leave very early for Berlin.

**Comment by alejoe91** [comment]
@colehurwitz fixed the read_binary and tested it. Also PR for spikecomparison and spikesorters are ready. Merging this!

**Comment by samuelgarcia** [comment]
Hi Cole, this uniformisation is cool.
I think we should merge soon and re run test on spikesorters/spikecomparison just fater.

**Comment by alejoe91** [comment]
merging!

**Pull request merged**
