### PR TITLE
Added extractor list, installation information, gui_params, naming, and installation messages.

### PR DESCRIPTION
**Pull request by colehurwitz31**
Planning to do the same for preprocessing and postprocessing.

### CODE REVIEW

**Comment by colehurwitz31** [comment]
@samuelgarcia I tried to copy your sorterlist format, but my extractorlist is not being recognized as a module. Could you possibly figure out what is going on?

**Comment by alejoe91** [comment]
@colehurwitz31 where is the extractorlist file?

**Comment by colehurwitz31** [comment]
Omg, I don't think I uploaded it... that explains it

**Comment by colehurwitz31** [comment]
Feel free to test out the installation and gui_params features to see if they give you the expected results. I will do the same for preprocessing and postprocessing if you guys think this is the correct way to proceed.

**Comment by colehurwitz31** [comment]
Something tricky is how we handle non-simple types like lists or arrays. I think we have to pass them in as a string in the GUI and then parse them into the more complex types.

**Comment by colehurwitz31** [comment]
I think I will merge soon. @samuelgarcia Do you think that this method of installation and gui_params is the right way forward for now? If so, I can implement this in preprocessing/postprocessing in spiketoolkit.

**Comment by samuelgarcia** [comment]
Very few times this week.
Sorry.
This looks good.
have you started UI with pyqtgraph parameters ?
have you tried ephyviewer ?

**Comment by colehurwitz31** [comment]
I looked at ephyviewer and left a comment about what I was confused about. I think I would need you to walk me through the purpose of the different viewers and what kinda feedback you are looking for.

**Pull request merged**
