### PR TITLE
Refractor save_to_probe_file

### PR DESCRIPTION
**Pull request by alejoe91**
This is to enforce writing of groups only when selected by the user (especially for spike sorting)

- added `grouping_property`
- removed `format` and added `graph`, `geometry`

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Whta a good initiative!

**Comment by samuelgarcia** [comment]
This looks good.
A unitest for this ?

Did you try this with the buggy example you send me ?

**Comment by alejoe91** [comment]
> This looks good.
> A unitest for this ?
> 
> Did you try this with the buggy example you send me ?

I added one in [test_extractors](https://github.com/SpikeInterface/spikeextractors/pull/301/files#diff-432ce628b2f5e01f964739fd8b4672ebR37-R53). Basically it checks that groups are saved/not saved. I tried with all sorters and they work!

**Comment by samuelgarcia** [comment]
Un champion.

Ok for me.

**Comment by alejoe91** [comment]
ok merging

**Pull request merged**
