### PR TITLE
Rename without upper case for file to avoid colision with class name.

### PR DESCRIPTION
**Pull request by samuelgarcia**
This is needed for spikeinterface metapackage.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
dir(spikeinterface.extractors) and dir(spikeextractors) still have differents length.

This is strange.

**Comment by alejoe91** [comment]
@samuelgarcia you can fix the tests by changing 
`from .SubRecordingExtractor`->`from .subrecordingextractor` in line 576 of recordingextractor.py
`from .SubSortingExtractor`->`from .subsortingextractor` in line 567 of sortingextractor.py

I tried to push from this PR but it creates a new branch...

Does this fix the import error of spikeinterface?

**Comment by samuelgarcia** [comment]
Hi Alessio, I will fix test tomorow.
No it do not fix the spikeinterface flat or not flat not everything is in the metapackage namespace.
I don't anderstand why, I will have a deeper look.
It could be a loop import somewhere.

**Comment by samuelgarcia** [comment]
normally you can push in my branch when it is a PR di you add the samuelgarcia/spikeextractors as remote ?

**Comment by samuelgarcia** [comment]
This pass test.
I think we can merge.
This do not fix the flat import but it is better this way.
no ?

**Comment by alejoe91** [comment]
Yes!

**Pull request merged**
