### PR TITLE
disabled shybrid test because pyqt5 install fails

### PR DESCRIPTION
**Pull request by colehurwitz**
Master branch is failing because the shybrid test no longer works (pyqt5 wont install on travis). I disabled it in this pull request. @alejoe91

### CODE REVIEW

**Comment by alejoe91** [comment]
@jwouters91 maybe you can force pyqt==5.13 in shybrid? We had a similar problem in spikesorters with tridesclous and spyking circus.

**Comment by colehurwitz** [comment]
I can try this

**Comment by jwouters91** [comment]
@alejoe91 @colehurwitz  I forced the version of pyqt to 5.13 and pushed those changes also to PyPI. Can you give it a try?

**Comment by alejoe91** [comment]
Just retriggered this https://github.com/SpikeInterface/spikeextractors/pull/291 which was failing for the same reason and it solves the issue.

Thanks @jwouters91!

@colehurwitz should be fixed now :) we can close this

**Pull request closed without merging**
