### PR TITLE
Added epoch functionality to sorting extractor

### PR DESCRIPTION
**Pull request by colehurwitz**
Very useful for quality metrics

### CODE REVIEW

**Comment by colehurwitz** [comment]
Also, adjusted an internal variable name :)

**Comment by alejoe91** [comment]
Looks great! Merge? You can also merge the spiketoolkit PR and the NWB changes imo

**Comment by colehurwitz** [comment]
I am almost done with the spiketoolkit PR

**Comment by alejoe91** [comment]
Merge the amplitudes one first, so you can incorporate the hist metric :)

**Comment by colehurwitz** [comment]
Yes, if you could quickly just make it ms_before and ms_after, we can merge.

**Comment by colehurwitz** [comment]
Then I will include amplitude cutoffs.

**Comment by alejoe91** [comment]
Commented there. Frames is correct as it doesn't compute waveforms, but small snippets around the peaks

**Pull request merged**
