### PR TITLE
updated code for yass

### PR DESCRIPTION
**Pull request by catubc**
Hi
This is the required sortingextractor for Yass to go along with spikesorter code.

### CODE REVIEW

**Comment by alejoe91** [comment]
The tasse extractor is already there: https://github.com/SpikeInterface/spikeextractors/tree/master/spikeextractors/extractors/yassextractors

**Comment by catubc** [comment]
Yes, it's all good now!

**Comment by alejoe91** [comment]
Ok I can close this then. Note that you pushed a lot of build folders which should not be pushed

**Comment by catubc** [comment]
Ok, removed build folder

**Comment by alejoe91** [comment]
@catubc I don't understand this Pr. You pushed an empty file when we already merges the YassSortingExtractor (https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/yassextractors/yassextractors.py).

Please also remove the dist stuff

**Comment by catubc** [comment]
Ok removed dist directory

Not sure what you mean by "empty file"?  I guess the original yassextractors.py file was empty?  But I thought you need the specific tools for loading yass data, which are not similar to other datasets.

Can you please clarify

**Comment by alejoe91** [comment]
> Ok removed dist directory
> 
> Not sure what you mean by "empty file"? I guess the original yassextractors.py file was empty? But I thought you need the specific tools for loading yass data, which are not similar to other datasets.
> 

You pushed an empty file: https://github.com/catubc/spikeextractors/blob/master/spikeextractors/extractors/yasssortingextractor/yasssortingextractor.py

> Can you please clarify

In spikeextractors we already have a full and working `YassSortingExtractor`: 

https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/yassextractors/yassextractors.py

**Comment by samuelgarcia** [comment]
Since build have been push I higly recommand the "squash and merge" otherwise it will keep build in history for ever.

**Comment by alejoe91** [comment]
> Since build have been push I higly recommand the "squash and merge" otherwise it will keep build in history for ever.

I don't think we need to merge this. The `YassSortingExtractor` is already in master

**Comment by catubc** [comment]
Not sure what squash and merge is, please let me know what else is required here from my end..

**Pull request closed without merging**
