### PR TITLE
Extractor fixes for biocam and hs2

### PR DESCRIPTION
**Pull request by mhhennig**
* better reading performance for Biocam files
* should now correctly detect different brw formats

### CODE REVIEW

**Comment by alejoe91** [comment]
is this ready to be merged?

**Comment by colehurwitz31** [comment]
Is the invert data removed from the bindat extractor

**Comment by mhhennig** [comment]
Yes, the invert is removes. For consistency I have decided we should use the preprocessing modules for this.Hee's a request, can we have, instead of the one that scales the data, a 'transformer', that does a*x+b, where a and b are arguments. This will be useful in quite a few cases where the data scale is off for the integer range HS2 expects.

**Comment by mhhennig** [comment]
Looks ready to me...

**Pull request merged**
