### PR TITLE
Updated mearec for h5 destructor

### PR DESCRIPTION
**Pull request by alejoe91**
Update to new h5 backend.

The recgen object need to be a member variable otherwise the underlying h5 file gets closed by the destructor

### CODE REVIEW

**Comment by colehurwitz** [comment]
Ok, if this fixes it then feel free to merge

**Comment by colehurwitz** [comment]
Still seems to be broken?

**Comment by alejoe91** [comment]
I don't know why it didn't trigger travis

**Comment by colehurwitz** [comment]
I think it did: https://travis-ci.org/SpikeInterface/spikeextractors

**Comment by alejoe91** [comment]
I forgot to switch back to the tempfile folder

**Comment by alejoe91** [comment]
ok fixed now, merging

**Pull request merged**
